### ISSUE TITLE
Can not add client node to cluster

### ISSUE THREAD

**Issue by modir** [ceph/ceph-ansible#5185]
What happened:
I created for a simple hosts file with 3 mons and 3 osds servers. I ran then ansible playbook and the installation went fine. Afterwards I wanted to add a client node to the cluster. So I added a new server under [clients] and started the playbook again. Now the playbook always crashes with this error message:

```
fatal: [server1]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'None' has no attribute 'get'
  
    The error appears to be in '/home/vagrant/ceph-ansible/roles/ceph-facts/tasks/facts.yml': line 296, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: set_fact osd_pool_default_pg_num
      ^ here
```
I don't see how this could be related in any way with my changes.

What you expected to happen:
I expect that the installation goes thru.

How to reproduce it (minimal and precise):
I removed now the client section from the hosts file and I still get the same error. So the problem comes up everytime I run the playbook again.

**Environment**:
* OS (e.g. from /etc/os-release): Centos 7
* Kernel (e.g. `uname -a`): Linux server1 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linu
* Docker version if applicable (e.g. `docker version`): 1.13.1
* Ansible version (e.g. `ansible-playbook --version`): 2.8.8
* ceph-ansible version (e.g. `git head or tag or stable branch`): at branch 4.0 commit ac2bd94cba542152e3dbf6014b283f1bdbe7e998 taken from 3 or 4 days ago.
* Ceph version (e.g. `ceph -v`): ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)

**Comment by guits** [comment]
same thing as usual, please share group_vars, inventory, full ceph-ansible log ...

**Comment by modir** [comment]
[ansible.zip](https://github.com/ceph/ceph-ansible/files/4382782/ansible.zip) here are the ansible log and the facts
[ceph-ansible.zip](https://github.com/ceph/ceph-ansible/files/4382785/ceph-ansible.zip) and here is the whole configuration including goup_vars
I edited to logs and all.yml to take out the passwords which were in clear text.

**Comment by modir** [comment]
I delivered what was asked for. I am waiting now.

**Comment by modir** [comment]
Maybe I would have to run a different playbook to do this but the documentation doesn't tell.

**Comment by guits** [comment]
@modir could you try again with a newer version of ceph-ansible? IIRC, we've pushed some patches that might fix your issue.

**Comment by modir** [comment]
@guits I tried it now with the newest version. Still the same:
`TASK [ceph-facts : set_fact osd_pool_default_pg_num] **********************************************************************************************************
Tuesday 28 April 2020  19:22:50 +0000 (0:00:00.200)       0:00:22.718 ********* 
fatal: [st-glb-r1-c10-u26.infra.huanga.com]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'None' has no attribute 'get'
  
    The error appears to be in '/home/vagrant/ceph-ansible/roles/ceph-facts/tasks/facts.yml': line 308, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: set_fact osd_pool_default_pg_num
      ^ here
fatal: [st-glb-r1-c10-u29.infra.huanga.com]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'None' has no attribute 'get'
  
    The error appears to be in '/home/vagrant/ceph-ansible/roles/ceph-facts/tasks/facts.yml': line 308, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: set_fact osd_pool_default_pg_num
      ^ here
fatal: [st-glb-r1-c10-u30.infra.huanga.com]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'None' has no attribute 'get'
  
    The error appears to be in '/home/vagrant/ceph-ansible/roles/ceph-facts/tasks/facts.yml': line 308, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: set_fact osd_pool_default_pg_num
      ^ here
`

**Comment by dsavineau** [comment]
This is coming from your configuration and especially the `ceph_conf_overrides` variable because you made a mistake.
I was able to reproduce the error with your configuration.

```yaml
ceph_conf_overrides:
  global:
#     foo: 1234
#     bar: 5678
  "client.rgw.{{ hostvars[groups.get(rgw_group_name)[0]]['ansible_hostname'] }}":
    rgw_zone: zone1
```

The `global` key doesn't have a value so the `ceph_conf_overrides.get('global', {})` fails.
If you remove the `global` key from the `ceph_conf_overrides` dict (which is useless) then the task succeed.
