### ISSUE TITLE
Add support for installing the ceph kernel client

### ISSUE THREAD

**Issue by batrick** [ceph/ceph-ansible#987]
I think this should be doable on VMs, e.g. from:

http://gitbuilder.sepia.ceph.com/gitbuilder-kernel-rpm-centos7-amd64-basic/

I'd like to do this for Linode but could use some advice/hints on what to do.

Copied from: http://tracker.ceph.com/issues/17305

**Comment by leseb** [comment]
Hum usually the Kernel client is already compiled with the client, an I missing something?

**Comment by batrick** [comment]
Are you saying the kernel module objects should be on the clients? I don't see them.

**Comment by leseb** [comment]
Which Kernel module are we talking about exactly?
Is it the rbd module?

**Comment by batrick** [comment]
The cephfs module.

**Comment by leseb** [comment]
Oh this one, well then into ceph-client please. Same place as https://github.com/ceph/ceph-ansible/issues/985

**Comment by leseb** [comment]
Done.

**Comment by batrick** [comment]
@leseb is this fixed in the upstream packages?

**Comment by leseb** [comment]
@batrick which upstream packages? ceph-ansible or ceph itself?

**Comment by leseb** [comment]
@batrick sorry, I think I had it wrong, this is not fixed and this deserves the same fix as https://github.com/joke-lee/ceph-ansible/commit/6e011d683814c3b0abd5f2583e29721f376faba1

**Comment by batrick** [comment]
@fullerdj can you take lead on this?

**Comment by fullerdj** [comment]
Sure.

**Comment by fullerdj** [comment]
@batrick So, the kcephfs module should come with the distribution kernel. (kernel-* on Red Hat flavors and kernel-image-* on Debian flavors). We can install our versions when ceph_dev is selected (which makes sense), but I think it should be optional. I'll work on that.

Linode stuffs its own kernel in its default images (which doesn't track the distro closely), so this wouldn't be a solution there. They don't seem to publish a repo for modules, so we could generate a custom image there.

**Comment by batrick** [comment]
> @batrick So, the kcephfs module should come with the distribution kernel. (kernel-* on Red Hat flavors and kernel-image-* on Debian flavors). We can install our versions when ceph_dev is selected (which makes sense), but I think it should be optional. I'll work on that.

So I'm not very knowledgeable on this but I would think we would always want to override whatever built-in/module is bundled with the kernel. From a quick google, this link:

https://stackoverflow.com/questions/29337119/override-duplicate-device-driver-for-kernel

indicates it should be possible. Or is that a problem because the kernel module we build may not be loadable by whatever particular old or new kernel the machine is using?

> Linode stuffs its own kernel in its default images (which doesn't track the distro closely), so this wouldn't be a solution there. They don't seem to publish a repo for modules, so we could generate a custom image there.

So ya, you can select from Linode's pre-built kernels but we can also force the Linodes to use the kernel provided by the distribution. This is done by setting GRUB in the Linode config and installing grub/kernel in the distribution).

**Comment by fullerdj** [comment]
> So I'm not very knowledgeable on this but I would think we would always want to override whatever built-in/module is bundled with the kernel. From a quick google, this link:
> 
> https://stackoverflow.com/questions/29337119/override-duplicate-device-driver-for-kernel
> 
> indicates it should be possible. Or is that a problem because the kernel module we build may not be loadable by whatever particular old or new kernel the machine is using?

That's the issue. We distribute our own fully-built kernel and modules (which is built from https://github.com/ceph/ceph-client, which doesn't track any distribution), which would ordinarily serve as a replacement for the kernel installed on the target system. We can install our RPM, but then the user would need to reboot using our kernel.

**Comment by batrick** [comment]
Okay well, perhaps a config option to install our kernel (based on branch, e.g. the usual "testing") and/or modules would be fine. If we install the kernel then ansible would need to reboot the machines which is not an uncommon thing to do. If the module can't be loaded then I guess it should FAIL and complain? What do you think?

**Comment by fullerdj** [comment]
Yes, that's what I was thinking.

**Comment by batrick** [comment]
Okay great, I pinged @ukernel by email on this in case he has any recommendations/thoughts.

**Comment by ukernel** [comment]
building ceph modules (from the newest upstream code) for old version kernel is not easy. Because the kernel internal changes from time to time. need to add lots "#if  kernel_version > xxxx ... #endif"
to the code. I think install full kernel package and reboot is better.

**Comment by fullerdj** [comment]
https://github.com/ceph/ceph-ansible/pull/1748
